resources/wrapper/godelw

* Add -f flag to cause call to fail on server errors
* Add -L flag to follow redirects
Fixes #15
Fixes #16

Update flags provided to curl call in godelw script

---

apps/distgo/cmd/publish/almanac.go
apps/distgo/cmd/publish/almanac_publish.go
apps/distgo/cmd/publish/almanac_test.go

Ensure that the error that is returned when an Almanac operation
fails does not include the authorization information in the header.
Fixes #26

Remove authorization header content from error

---

cmd/packages/cmd.go
config/config.go
config/example_test.go

Match standards and conventions used by subapps.

Update configuration functions for exclude configuration

---

apps/gunit/cmd/global.go
apps/gunit/cmd/test/test.go
apps/gunit/integration_test/integration_test.go

Add '--race' flag to test command

---

cmd/idea/idea.go

Fix program argument for FileWatchers plugin

---

apps/distgo/cmd/run/cmd.go
apps/distgo/integration_test/doc.go
apps/distgo/integration_test/integration_test.go
integration_test/integration_test.go

Update disto 'run' command to accept arguments

---

apps/distgo/cmd/dist/dist_test.go
apps/distgo/cmd/dist/slsdist.go
apps/distgo/config/config.go
apps/distgo/config/config_test.go
apps/distgo/config/example_test.go
apps/distgo/params/dist.go

Fixes #51 
@nmiyake sorry the ticket was unclear, this is what I'm thinking
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/godel/52)

Add optional init.sh reload

---

apps/distgo/cmd/dist/rpmdist.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/godel/58)

Always build RPMs for Linux. Fixes #7

---

apps/distgo/pkg/git/git.go
apps/distgo/pkg/git/git_test.go
apps/distgo/pkg/git/gittest/gittest.go

Use '--first-parent' in git describe calls

---

apps/gunit/cmd/global.go
apps/gunit/config/config_test.go
apps/gunit/integration_test/integration_test.go
apps/gunit/params/params.go

Add 'all' tag that runs all tests

---

apps/distgo/cmd/dist/dist.go
apps/distgo/cmd/dist/dockerdist.go
apps/distgo/cmd/dist/dockertests/dist_docker_test.go
apps/distgo/cmd/dist/order_specs.go
apps/distgo/cmd/dist/order_specs_test.go
apps/distgo/params/dist.go
apps/distgo/params/product.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/godel/97)

Copy dist deps to docker context dir in distgo

---

apps/distgo/config/config.go
apps/distgo/config/config_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/godel/99)

Add docker config

---

apps/distgo/cmd/docker/build.go
apps/distgo/cmd/docker/build_test.go
apps/distgo/cmd/docker/cmd.go
apps/distgo/cmd/docker/publish.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/godel/104)

add publish task for docker images

---

apps/distgo/cmd/run/run.go
apps/distgo/integration_test/integration_test.go

Add support for flags in 'run' command

---

apps/distgo/cmd/run/run.go
apps/distgo/integration_test/integration_test.go

Attach os.Stdin to stdin of program started by disto run command

---

apps/distgo/cmd/dist/dist_test.go
apps/distgo/cmd/publish/pom.go
apps/distgo/cmd/publish/pom_test.go
apps/distgo/cmd/publish/publish.go
apps/distgo/cmd/publish/publish_test.go
apps/distgo/config/config.go
apps/distgo/params/params.go
apps/distgo/params/product.go

* Separate POM generation to separate file
* Rename DefaultPublish to Publish in parameters
* Make tests more readable

Refactor some publish logic

---

apps/distgo/cmd/publish/publish_test.go

Add tests for products with multiple OS/Arch distributions.

Add publish tests

---

apps/distgo/cmd/publish/cmd.go
apps/distgo/cmd/publish/github_publish.go
apps/distgo/cmd/publish/github_publish_test.go
godel/config/check.yml
vendor/github.com/jtacoma/uritemplates/LICENSE
vendor/github.com/jtacoma/uritemplates/uritemplates.go
vendor/vendor.json

this fails the `novendor` check on `github.com/google/go-querystring` and I don't know why...

automatically detect github upload URI

---

godel/config/check.yml

Update the comment to refer to the issue that actually causes
the exemption to be necessary.

Update comment on novendor filter entry

---

apps/okgo/generated_src/internal/github.com/palantir/checks/novendor/novendor.go
vendor/github.com/palantir/checks/novendor/novendor.go
vendor/vendor.json

This reverts commit 26302f1cb9a5039b20096b3f9dc146c8c51650f5.

Revert "Update novendor check (#145)"

---

godel/config/check.yml

Use "--ignore" flag rather than matching output lines.

Update novendor configuration

---

apps/okgo/generated_src/internal/github.com/palantir/checks/novendor/novendor.go
apps/okgo/vendor/github.com/palantir/checks/novendor/novendor.go
apps/okgo/vendor/vendor.json

Update checks dependency

---

apps/gunit/cmd/global.go
apps/gunit/integration_test/integration_test.go

Make gunit test deal with keys with capitalization correctly

---

apps/gunit/app_test.go
apps/gunit/cmd/global.go
apps/gunit/integration_test/integration_test.go

Improve error message for invalid tags

---

apps/gunit/app_test.go
apps/gunit/cmd/global.go

Ensures that error output is stable.

Sort tags alphabetically in error output

---

apps/distgo/cmd/publish/github_publish.go

Append trailing slash to GitHub upload URL if it is missing

---

apps/distgo/cmd/publish/github_publish.go
apps/distgo/pkg/git/git.go

Require repository to be on tagged commit for GitHub publish task

---

apps/distgo/cmd/publish/almanac.go
apps/distgo/cmd/publish/almanac_publish.go
apps/distgo/cmd/publish/almanac_test.go

Add output for Almanac publish operation

---

cmd/checkpath/checkpath.go
cmd/checkpath/cmd.go

Change "info" flag to "apply" and change the default behavior so
that the command prints the suggested steps rather than executing
them.
Fixes #6

Update check-path command

---

integration_test/integration_test.go
vendor/github.com/palantir/checks/gogenerate/gogenerate/generate.go
vendor/vendor.json

Updates gogenerate to change indentation of output

Update palantir/checks dependency

---

.circleci/config.yml

Unify more of the common logic to simpify configuration.

Refactor CircleCI test steps definition

---

apps/distgo/cmd/docker/build.go
apps/distgo/cmd/docker/cmd.go
apps/distgo/cmd/docker/products.go
apps/distgo/cmd/docker/products_test.go
apps/distgo/cmd/docker/publish.go

Add ability to build/publish specific docker images

---

framework/pluginapi/pflags.go

Fixes bug that caused ConfigFlagName flags to not be added properly.

Fix AddConfigPFlag functions

---

pkg/dirchecksum/cleanup.go
pkg/dirchecksum/verify.go
pkg/gocd_imports.json

Make cleanup an implementation detail of dirchecksum and expose
combined ChecksumForDirAction function.

Combine cleanup package with dirchecksum

---

.circleci/config.yml

Ensures that cache takes plugin content into consideration.

Update CircleCI cache to include godel.yml

---

apps/distgo/pkg/script/script.go

Ensure that proper variables are set/provided for the BuildArgsScript.

Fix variables provided to BuildArgsScript

---

apps/distgo/params/build.go

Fix typo in comment

---

apps/distgo/cmd/dist/slsdist.go

Keeping at least MAX_STARTUP_LOG_FILE_SIZE startup logs

Backing up startup log file

---

framework/pluginapi/globalflagopts.go
framework/pluginapi/info.go
framework/pluginapi/taskinfo.go
framework/pluginapi/verifyopts.go

Change interface implementations from using pointer receivers to
value receivers. Fixes a class of bugs where ranging over pointers
and converting them could cause bugs.

Change interface implementations to use value receivers

---

framework/godellauncher/config.go

This logic is no longer required for 2.0.

Remove JSON serialization logic

---

godelinit/README.md

Change "go install" to "go get".

Update godelinit README

---

Gopkg.lock
Gopkg.toml
vendor/github.com/palantir/distgo/.circleci/config.yml
vendor/github.com/palantir/distgo/README.md
vendor/github.com/palantir/distgo/cmd/dist.go
vendor/github.com/palantir/distgo/cmd/docker.go
vendor/github.com/palantir/distgo/cmd/publish.go
vendor/github.com/palantir/distgo/cmd/root.go
vendor/github.com/palantir/distgo/dister/dister_manual.go
vendor/github.com/palantir/distgo/distgo/artifacts/artifacts.go
vendor/github.com/palantir/distgo/distgo/artifacts/artifacts_test.go
vendor/github.com/palantir/distgo/distgo/build/build_test.go
vendor/github.com/palantir/distgo/distgo/clean/clean_test.go
vendor/github.com/palantir/distgo/distgo/configdist.go
vendor/github.com/palantir/distgo/distgo/dist/dist.go
vendor/github.com/palantir/distgo/distgo/dist/dist_test.go
vendor/github.com/palantir/distgo/distgo/dist/requiresdist.go
vendor/github.com/palantir/distgo/distgo/docker/docker_build.go
vendor/github.com/palantir/distgo/distgo/docker/docker_build_test.go
vendor/github.com/palantir/distgo/distgo/publish/publish.go
vendor/github.com/palantir/distgo/distgo/publish/publish_test.go
vendor/github.com/palantir/distgo/godel/config/dist.yml
vendor/github.com/palantir/distgo/pkg/git/git.go
vendor/github.com/palantir/distgo/pkg/git/git_test.go
vendor/github.com/palantir/distgo/publisher/common.go
vendor/github.com/palantir/distgo/publisher/publisher_artifactory.go
vendor/github.com/palantir/distgo/publisher/publisher_artifactory_test.go
vendor/github.com/palantir/distgo/publisher/publisher_bintray.go
vendor/github.com/palantir/distgo/publisher/publisher_bintray_test.go
vendor/github.com/palantir/distgo/publisher/publisher_test.go

Required to handle tags with 'v' prefix.

Update distgo dependency

---

framework/builtintasks/checkpath.go
framework/builtintasks/githooks.go
framework/builtintasks/githubwiki.go
framework/builtintasks/idea.go
framework/builtintasks/info.go
framework/builtintasks/install.go
framework/builtintasks/packages.go
framework/builtintasks/pluginsconfig.go
framework/builtintasks/tasks.go
framework/builtintasks/update.go
framework/builtintasks/version.go
framework/godellauncher/cobraclitask.go
framework/godellauncher/globalconfig.go
main.go

Add pointer to global configuration to CobraCLITask function
so that project directory can be determined properly.

Improve API for built-in tasks

---

pkg/gocd_imports.json
pkg/v2/products/products.go
pkg/v2/products/products_test.go

Restore "pkg/products" package API to v1 state and introduce new
"pkg/v2/products" package for v2 functionality.

Separate pkg/products into v1 and v2 API

---

framework/builtintasks/upgradeconfig.go
framework/builtintasks/upgradelegacyconfig.go
framework/godellauncher/config.go
framework/godellauncher/config_test.go
framework/godellauncher/defaultupgradetasks.go
framework/godellauncher/upgradeconfigtask.go
framework/internal/legacyplugins/legacyplugins.go
framework/pluginapi/cobracli.go
framework/pluginapi/globalflagopts.go
framework/pluginapi/plugininfo.go
framework/pluginapi/plugininfo_test.go
framework/pluginapi/taskinfo.go
framework/pluginapi/upgradeconfigtaskinfo.go
framework/pluginapitester/plugintester.go
framework/pluginapitester/providers.go
framework/pluginapitester/upgradeconfigtester.go
framework/plugins/plugin.go
framework/plugins/plugin_test.go
godelconfig/VersionedConfig.go
integration_test/plugins_test.go
main.go
pkg/gocd_imports.json
pkg/versionedconfig/versionedconfig.go

Add upgrade-config and upgrade-legacy-config tasks

---

framework/pluginapitester/upgradeconfigtester.go

Output full content of actual file for easier debugging.

Update output of config upgrade tester on error

---

framework/builtintasks/upgradelegacyconfig.go

Use plugin providers and provide better output for upgrades.

Make improvements to upgrade-legacy-config task

---

framework/godellauncher/defaulttasks/defaulttasks.go
framework/godellauncher/defaulttasks/defaulttasks_test.go
main.go

Print an error if overrides are specified for a default plugin
that is not loaded.

Improve handling of nonexistent plugins in default config

---

framework/builtintasks/install.go
framework/builtintasks/installupdate/godelwcmds.go
framework/builtintasks/installupdate/upgradeafterupdate.go
framework/builtintasks/installupdate/versionparser.go
framework/builtintasks/update.go
godelinit/root.go

Also refactor logic that is used to determine whether or not
upgrade should be performed.

Update 'install' task to upgrade config when appropriate

---

framework/builtintasks/install.go

Allows expected checksum to be specified.

Add '--checksum' flag to 'install' task

---

godelinit/root.go

Adds ability for godelinit to install a local package.

Add '--local' flag to godelinit

---

framework/godellauncher/defaulttasks/defaulttasks.go

Use new standalone repository.

Update default version of license-plugin

---

framework/godellauncher/defaulttasks/defaulttasks.go

Update default version of outparamcheck to 1.1.1

---

framework/godellauncher/defaulttasks/defaulttasks.go

@nmiyake I took the checksums from https://bintray.com/palantir/releases/distgo which is I assume the correct place

Upgrade distgo to 1.13.0

---

Gopkg.lock
Gopkg.toml
vendor/github.com/palantir/pkg/cobracli/default.go
vendor/github.com/palantir/pkg/cobracli/execute.go
vendor/github.com/palantir/pkg/cobracli/version.go
vendor/github.com/palantir/pkg/gittest/gittest.go
vendor/github.com/palantir/pkg/godel/config/license-plugin.yml
vendor/github.com/palantir/pkg/matcher/config.go
vendor/github.com/palantir/pkg/matcher/files.go
vendor/github.com/palantir/pkg/matcher/matchers.go
vendor/github.com/palantir/pkg/pkgpath/packages.go
vendor/github.com/palantir/pkg/signals/signals.go
vendor/github.com/palantir/pkg/specdir/node.go
vendor/github.com/palantir/pkg/specdir/spec.go
vendor/github.com/palantir/pkg/specdir/specdir.go
vendor/github.com/palantir/pkg/uuid/internal/uuid/LICENSE

Now that pkg is versioned, this is helpful for projects vendoring the plugin API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/godel/431)

Bump palantir/pkg dependency

---

framework/godel/config/readconfig.go
framework/godel/config/readconfig_test.go

Allows library to read only exclude portion of configuration.
Fixes #447

Add ReadGodelConfigExcludesFromFile function

---

.changelog.yml

Add changelog configuration file

---

go.mod
go.sum
vendor/github.com/mattn/go-colorable/colorable_appengine.go
vendor/github.com/mattn/go-colorable/colorable_others.go
vendor/github.com/mattn/go-colorable/colorable_windows.go
vendor/github.com/mattn/go-colorable/noncolorable.go
vendor/modules.txt

Remove unneeded indirect module require

---

changelog/@unreleased/pr-499.v2.yml

Perform a release to fix tagging issue.

Empty commit for release

---

.circleci/config.yml
changelog/@unreleased/pr-508.v2.yml

Updates Go version used to build godel to 1.14.

Improvement: update Go versions to 1.14

---

.circleci/config.yml
changelog/@unreleased/pr-514.v2.yml

==COMMIT_MSG==
Update go version used to build to 1.14.4.
==COMMIT_MSG==

Update go version to 1.14.4

---

changelog/@unreleased/pr-515.v2.yml
framework/godellauncher/defaulttasks/defaulttasks.go

==COMMIT_MSG==
Update plugins and assets to versions built with Go 1.14.4.
==COMMIT_MSG==

Update plugins and assets

---

changelog/@unreleased/pr-526.yml
framework/godellauncher/defaulttasks/defaulttasks.go

==COMMIT_MSG==
Upgrade distgo to 1.24.0
==COMMIT_MSG==
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/godel/526)

Upgrade distgo to 1.24.0

---

changelog/@unreleased/pr-545.v2.yml
framework/godellauncher/defaulttasks/defaulttasks.go

==COMMIT_MSG==
Updates distgo version to use 1.25.0.
==COMMIT_MSG==

Update distgo version to 1.25.0

---

.circleci/config.yml
changelog/@unreleased/pr-547.v2.yml

Also removes references to custom images.

Update CircleCI configuration to use Go 1.16

---

changelog/@unreleased/pr-551.v2.yml
framework/godellauncher/defaulttasks/defaulttasks.go

Update distgo to 1.26.0

---

changelog/@unreleased/pr-554.v2.yml
framework/builtintasks/installupdate/update.go

Update godel resolver to use GitHub releases

---

README.md

Remove Bintray badge from README

---

changelog/@unreleased/pr-567.v2.yml
godel/config/godel.properties
godelw

==COMMIT_MSG==
Updates version of godel used for project to 2.36.0
==COMMIT_MSG==

Update godel version to 2.36.0

---

godelinit/README.md

Update instructions to use "go install" with module version and
version suffix.
==COMMIT_MSG==
==COMMIT_MSG==

Update godelinit installation instructions

---

changelog/@unreleased/pr-595.v2.yml
framework/godellauncher/defaulttasks/defaulttasks.go

improvement: Upgrade godel-test-plugin to 1.8.0

---

godelinit/README.md

Code blocks now support an automatic copy utility whereas inline code sections do not. This will prevent users from manually copying and will hopefully reduce a class of developer errors.
==COMMIT_MSG==
Use a code-block for the installation command for easy copying
==COMMIT_MSG==
https://user-images.githubusercontent.com/5448017/145092684-b8e11c23-3837-4d26-9d4c-531e03aa8bec.mov

Use a code-block for the installation command for easy copying

---

changelog/@unreleased/pr-667.v2.yml
framework/godellauncher/defaulttasks/defaulttasks.go

Includes https://github.com/palantir/distgo/pull/268

improvement: Upgrade distgo to 1.43.0

---

changelog/@unreleased/pr-830.v2.yml
framework/builtintasks/packages/packages.go
framework/builtintasks/packages/packages_test.go
go.mod
go.sum
vendor/github.com/palantir/pkg/pkgpath/godelw
vendor/github.com/palantir/pkg/pkgpath/packages.go
vendor/golang.org/x/mod/internal/lazyregexp/lazyre.go
vendor/golang.org/x/mod/modfile/print.go
vendor/golang.org/x/mod/modfile/read.go
vendor/golang.org/x/mod/modfile/rule.go
vendor/golang.org/x/mod/modfile/work.go
vendor/golang.org/x/mod/module/module.go
vendor/golang.org/x/mod/module/pseudo.go
vendor/modules.txt

==COMMIT_MSG==
Makes it so that the "packages" command only returns packages that are part of the same module as the module of the project root directory.
==COMMIT_MSG==

Update "packages" command to consider modules
