resources/wrapper/godelw
Ensures that comparisons are done in a safe manner even if one
of the variables is empty.
Fixes #19
=> Fix checksum comparison operation in godelw

resources/wrapper/godelw
If downloading the distribution using wget fails and curl also
exists on the system, attempt the download using curl. Also
adds more details to the error message (including command run)
and more granular progress through the steps.
Fixes #14
=> Update godelw script to fall back on curl if wget download fails

apps/distgo/pkg/git/git.go
Set working directory directly on the Go command executor instead.
Fixes #50
=> Remove use of '-C' flag in Git commands

circle.yml
Use tags that include version number to ensure that they are
immutable and safe to cache between runs.
=> Update Docker image references in circle.yml

apps/okgo/app.go, apps/okgo/cmd/check.go, apps/okgo/config/config.go, apps/okgo/config/example_test.go, apps/okgo/integration_test/integration_test.go, apps/okgo/params/params.go
Add a new "release-tag" configuration key that can be
used to specify the newest Go release tag that should
be used when checking Go files. Useful if the check
tool is used on a project that is being built with a
version of Go that is older than that used by the tool.
Fixes #72
=> Add support for specifying release tag for okgo checks

apps/gunit/cmd/test/test.go, apps/gunit/cmd/test/test_test.go
When determining the package for a directory, parse it using the
build context so that files that are excluded by build constraints
are not considered candidates for the package name. Also fix so
that, when there are multiple package matches, iteration order is
deterministic.
Fixes #79
=> Use build constraints when generating placeholder test files

apps/distgo/app.go, apps/distgo/cmd/projectversion/cmd.go, apps/distgo/cmd/projectversion/projectversion.go, apps/distgo/integration_test/integration_test.go, cmd/clicmds/cfgcli.go, integration_test/integration_test.go
* Add "project-version" command to distgo that prints the version
used for build/dist commands.
* Add "project-version" command to gödel that calls distgo command
Fixes #92
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/godel/93)
=> Add project-version command

apps/gunit/config/config.go, apps/gunit/config/config_test.go, apps/gunit/config/example_test.go, apps/gunit/integration_test/integration_test.go, vendor/github.com/palantir/pkg/matcher/config.go, vendor/github.com/palantir/pkg/matcher/files.go, vendor/github.com/palantir/pkg/matcher/matchers.go, vendor/vendor.json
Allows tags to exclude specific files or paths from matching.
=> Update gunit tags to use NamesPathsWithExcludeCfg

apps/distgo/cmd/dist/dist.go, apps/distgo/cmd/dist/dist_test.go, apps/distgo/cmd/dist/osarchbindist.go, apps/distgo/config/config.go, apps/distgo/params/dist.go
Adds a new distribution type for a tgz that creates a TGZ that
contains the executable for a specified OS/Arch.
Fixes #98
=> Add OSArchDist as a new dist type

apps/distgo/cmd/artifacts/artifacts.go, apps/distgo/cmd/dist/bindist.go, apps/distgo/cmd/dist/dist.go, apps/distgo/cmd/dist/osarchbindist.go, apps/distgo/cmd/dist/rpmdist.go, apps/distgo/cmd/dist/slsdist.go, apps/distgo/cmd/dist/types.go, apps/distgo/cmd/docker/build.go, apps/distgo/cmd/publish/publish.go
Use a more specific typing system to make it easier to add new
dist types and to keep track of the logic shared between different
aspects of a dist type.
=> Refactor dist types to centralize logic

apps/distgo/cmd/artifacts/artifacts.go, apps/distgo/cmd/artifacts/artifacts_test.go, apps/distgo/cmd/artifacts/cmd.go, apps/distgo/cmd/dist/bindist.go, apps/distgo/cmd/dist/dist.go, apps/distgo/cmd/dist/dist_test.go, apps/distgo/cmd/dist/dister.go, apps/distgo/cmd/dist/osarchbindist.go, apps/distgo/cmd/dist/rpmdist.go, apps/distgo/cmd/dist/slsdist.go, apps/distgo/cmd/docker/build.go, apps/distgo/cmd/publish/artifactory_publish.go, apps/distgo/cmd/publish/bintray_publish.go, apps/distgo/cmd/publish/cmd_test.go, apps/distgo/cmd/publish/local_publish.go, apps/distgo/cmd/publish/publish.go, apps/distgo/cmd/publish/publish_test.go, apps/distgo/config/config.go, apps/distgo/params/dist.go
Makes it possible to support the notion of classifiers (a single
distribution with multiple outputs of the same type). Updates
Publish code so that POM for dist is published once per set of
artifacts for a particular distribution.
Also fixes bug in "artifacts" where, if there were multiple
Dist configurations of the same type for a single product, only
the outputs for one of them would be reported.
Fixes #98
=> Add support for generating multiple artifacts per dist

apps/distgo/cmd/dist/dist_test.go, apps/distgo/cmd/dist/osarchbindist.go
Ensure that executable for proper platform is archived. Before
this fix, executables for different OS/Archs in a single dist
config would overwrite the previous one such that only the last
executable would be archived.
=> Fix bug in OSArchs dist type

apps/distgo/cmd/dist/dist_test.go, apps/distgo/config/config.go, apps/distgo/params/dist.go, apps/distgo/params/product.go
Mirror behavior of build OS/Arch parameter and allow the OS/Archs
combination to be empty. If it is empty, it will default to
creating a distribution for the OS/Arch combination at runtime.
Fixes #128
=> Make it so that os-archs property of os-arch-bin is optional

vendor/github.com/palantir/pkg/pkgpath/packages.go, vendor/vendor.json
Fixes bug where determining the packages in a project would fail
if a directory or file could not be read, even if that directory
or file was excluded via configuration.
Fixes #136
=> Update pkg/pkgpath dependency

apps/distgo/config/config_test.go
Standardize on 2-space indentation for YML in tests.
=> Fix indentation in config_test.go

apps/okgo/generated_src/internal/github.com/kisielk/errcheck/internal/errcheck/errcheck.go, apps/okgo/generated_src/internal/github.com/kisielk/errcheck/main.go, apps/okgo/integration_test/integration_test.go, vendor/github.com/kisielk/errcheck/internal/errcheck/errcheck.go, vendor/github.com/kisielk/errcheck/main.go, vendor/vendor.json
Specifically, to use the functionality provided by [kisielk/errcheck#116](https://github.com/kisielk/errcheck/pull/116).
=> Repackage a newer version of errcheck in order to use file-backed exclusion

apps/distgo/params/product.go
Change it so that default targets of the os-arch-bin dist type
match the os/arch types of the input build artifacts.
=> Update default value for os-arch-bin dist type

apps/distgo/cmd/dist/dist_test.go, apps/distgo/config/config.go, apps/distgo/config/config_test.go
Make it so that not specifying "omit-init-sh" is config is
equivalent to setting the value to "true" (rather than "false").
=> Change behavior of bin dist when omit-init-sh is not specified

apps/distgo/cmd/clean/clean.go, apps/distgo/cmd/clean/clean_test.go
If build output directory does not exist or cannot be read, treat
as a no-op instead of returning an error.
=> Make clean command work when build output directory does not exist

apps/distgo/cmd/publish/almanac.go, apps/distgo/cmd/publish/artifactory_publish.go, apps/distgo/cmd/publish/bintray_publish.go, apps/distgo/cmd/publish/cmd_test.go, apps/distgo/cmd/publish/local_publish.go, apps/distgo/cmd/publish/publish.go
Use %s rather than %v when printing string variables and clean
up minor style issues.
=> Touch up format strings and style in distgo

apps/gunit/app_test.go, apps/gunit/cmd/global.go, apps/gunit/cmd/test/test.go, apps/gunit/integration_test/integration_test.go, apps/gunit/params/params.go
Update the mental model and behavior of test tags.
* Running test task  without specifying any tags will now always run
all tests (previously, this would only run untagged tests)
* Running test task with "--tags=all" will now run union of all tagged
tests (previously, this would run all tagged and untagged tests)
* Running test task with "--tags=none" will now run only the untagged
tests (this option did not previously exist and was the behavior when
no tags were specified)
This change also makes it so that the "verify" task will run all tests
rather than just untagged tests.
=> Change behavior of test tags

cmd/verify/cmd.go, integration_test/integration_verify_test.go
Default behavior for '--verify' now runs all tests rather than
only untagged tests. The '--untagged-only' flag can be provided
to the '--verify' command to match the previous behavior.
=> Change default '--verify' behavior to run all tests

apps/distgo/pkg/git/git.go
Value was inadvertently changed from "unspecified" to "Unspecified".
=> Fix regression in value of 'unspecified' string

cmd/githubwiki/githubwiki.go
Print output of git command in addition to error in error output.
=> Add more detailed output for github-wiki task

apps/distgo/cmd/artifacts/artifacts.go, apps/distgo/cmd/artifacts/artifacts_test.go, apps/distgo/cmd/artifacts/cmd.go, apps/distgo/cmd/docker/products.go, apps/distgo/cmd/docker/products_test.go
Add "docker" subcommand that prints all of the tags that will be
created for a product.
Fixes #219
=> Add "docker" subommand to "artifacts" task

cmd/checkpath/checkpath.go, cmd/checkpath/checkpath_unix.go, cmd/checkpath/checkpath_windows.go
Fighting with running Godel on win10+VSCode without wanting to shiv myself; still need to write up godelw.ps1 and how to generate it, but this was the only chunk of os-specific code I found in build, so at least we can build under GOOS=windows, so it's a step in the right direction.
=> Checkpath os-specific logic so godel can build on windows.

framework/builtintasks/verify.go
Print error output to stdout and return error with empty content
so that output is not prefaced with "Error: ".
=> Fix output of 'verify' task

apps/distgo/cmd/publish/bintray_publish.go, apps/distgo/cmd/publish/cmd.go
Add '--product' flag to Bintray publish to allow Bintray product
name to be specified independently of publish product name.
=> Allow product to be specified for Bintray publish

framework/plugins/resolver.go, godelgetter/download.go
Make it so that "install" task does not download package if the
package source is the same as the download destination.
=> Fix install task

framework/builtintasks/installupdate/update.go, framework/builtintasks/installupdate/update_test.go, framework/builtintasks/update.go, godelinit/root.go
Make it so that, when 'update' is run with the '--sync' flag set
to 'false', it updates gödel to the latest version.
=> Update implementation of 'update' task

godelgetter/download.go, godelgetter/download_test.go, godelgetter/pkg.go
Ensure that destination file is not truncated if source reader
cannot be created and improve logic in interface.
=> Fix minor godelgetter issues

framework/internal/pathsinternal/plugins.go, framework/pluginapitester/assettester.go, framework/pluginapitester/plugintester.go, framework/plugins/configprovider.go, framework/plugins/plugin.go, framework/plugins/plugin_test.go
Adds new pluginapitester package to allow plugin and asset
projects test functionality. Also refactors some APIs to
use internal packages to allow for this.
=> Add pluginapitester package

framework/pluginapi/taskinfo.go
Ensures that all plugin output is captured properly.
=> Set stderr of plugin tasks to write to provided writer

framework/godellauncher/projectpaths.go, framework/godellauncher/projectpaths_test.go
Adds function that can be used to list all of the paths in a
project directory using matchers in a canonical manner. Can be
used by plugins and assets.
=> Add ListProjectPaths function

framework/pluginapi/verifyopts.go
Make the task flag option additive rather than having it set
the variable. Reduces a class of bugs where verify options
are specifeid as multiple options parameters rather than as
a single parameter with multiple flags.
=> Change VerifyOptionsTaskFlags to be additive

framework/builtintasks/update.go
Makes it so that default behavior of "update" updates to the
lastest published version rather than the version specified in
the properties file.
=> Default "--sync" flag of "update" task to false

framework/builtintasks/installupdate/update.go
If the tag name for the latest version retrieved from GitHub starts
with a 'v' followed by a digit, trim the leading 'v'.
=> Handle leading 'v' in godelinit

framework/builtintasks/installupdate/update.go
If a desired checksum is provided and the checksum of the
downloaded package does not match the desired checksum, re-download
the package. If the checksum of the re-downloaded package does not
match the desired checksum, the operation will fail.
=> Ensure that desired checksum is used properly

framework/builtintasks/upgradeconfig.go, framework/builtintasks/upgradelegacyconfig.go, framework/pluginapi/upgradeconfigtaskinfo.go
Output config upgrade errors using relative paths and remove
trailing ": exit 1" outputs.
=> Improve error output for config upgrade failures.

pkg/gocd_imports.json, pkg/versionedconfig/legacy.go, pkg/versionedconfig/unsupported.go, pkg/versionedconfig/unsupported_test.go
Add functions for standardizing behavior for dealing with legacy
configuration and dealing with the case where configuration is not
currently supported.
=> Add functions to versionedconfig package

framework/builtintasks/installupdate/godelwcmds.go, framework/builtintasks/installupdate/install.go, framework/builtintasks/installupdate/versionparser.go, framework/builtintasks/update.go, godelinit/root.go
Make it so that the "update" task runs "upgrade-config" if needed.
Also make it so that godelinit invokes "upgrade-legacy-config" or
"upgrade-config" as needed.
=> Run upgrade-config tasks on update or godelinit

main.go
Make it so that default task values specified in the config file
override any values provided by external config providers.
=> Fix task config resolution precedence

framework/godellauncher/defaulttasks/defaulttasks.go
Adds support for specifying the flag "--verify=false" to run
checks serially rather than in parallel.
Fixes #425
=> Update okgo plugin to 1.6.0

framework/artifactresolver/param.go, framework/godel/config/godel.go, framework/godel/config/internal/v0/godel.go, framework/godel/config/internal/v0/upgradeconfig.go, framework/plugins/configprovider.go, integration_test/integration_test.go, integration_test/plugins_test.go
Add "override" property to plugin configuration and allow it
to be used to override plugins specified in configuration providers.
Fixes #427
=> Implement plugin overrides

framework/builtintasks/exec.go, integration_test/integration_test.go
Add a built-in "exec" task that executes a given shell command
(with the provided flags and arguments) using godel. Useful for
running commands using the same environment variables set by
godel for its tasks.
=> Feature: add exec task

changelog/@unreleased/pr-503.v2.yml, framework/builtintasks/installupdate/godelwcmds.go, framework/builtintasks/installupdate/godelwcmds_test.go
Map all unicode line break runes to "\n" before splitting on
newlines. Fixes an issue where the version output would sometimes
not be parsed properly due to unicode linebreaks being used.
=> Fix: handle unicode line breaks when determining version

changelog/@unreleased/pr-504.v2.yml, framework/builtintasks/installupdate/godelwcmds.go
If parsing parts fails, output quoted version of input.
=> Fix: include quoted output in parse error

changelog/@unreleased/pr-505.v2.yml, framework/builtintasks/installupdate/godelwcmds.go, framework/builtintasks/installupdate/godelwcmds_test.go, godelgetter/download.go
Explicitly set the return symbol for progress bars so that
returns and newlines are always added, even when not in terminal
mode.
Also changes splitting logic to only split on "\r" and "\n" rather
than on all Unicode line break characters.
=> Fix: always output newlines after progress

.circleci/config.yml, changelog/@unreleased/pr-525.v2.yml
brew-go image was historically part of integration tests to ensure that GOROOT/GOPATH issues did not occur when using Go installed by `brew` (as opposed to a standard installation). This was particularly relevant in situations where a project was attempting to be built outside the GOPATH.
==COMMIT_MSG==
Removes brew-go environment in CircleCI from integration tests. Now that most projects use Go modules, GOPATH and GOROOT have much less significance and specifically testing in an environment where go is installed using `brew` is less imoprtant.
==COMMIT_MSG==
=> Remove brew-go image from CircleCI

changelog/@unreleased/pr-536.v2.yml, framework/pluginapi/plugininfo.go, framework/pluginapi/v2/pluginapi/plugininfo.go
Getting task information for plugins can fail when multiple instances of godel are resolving artifacts concurrently
==COMMIT_MSG==
Fixes issue where getting plugin information could fail when multiple instances of godel are performing resolution concurrently. Note that, in order for this fix to work, all of the copies of godel that are running concurrently must have this fix.
==COMMIT_MSG==
Makes plugin resolution more resilient to concurrent runs of
godel.
Fixes #535
=> Lock plugin files when getting task information

changelog/@unreleased/pr-537.v2.yml, framework/plugins/plugin.go
Prior to this PR, attempts were made to fix issues with concurrent resolution of godel files (#533, #535) by locking individual files while they were being downloaded, verified and executed (#534, #535).
However, the previous approaches did not fully work and also suffered from a whack-a-mole problem where we had to ensure that every individual operation that operated on a file that could be resolved had to lock the file. Additionally, that locking mechanism often still led to duplicated work: if process 1 and process 2 both saw that a file did not exist, although process 2 would wait for process 1 to download the file before proceeding, after process 1 released the lock process 2 would then acquire the lock and perform the same download again.
==COMMIT_MSG==
Introduces a new …
=> Require plugin resolution to lock godel-resolver.lock file

framework/artifactresolver/resolver.go, framework/internal/pluginsinternal/plugins.go, framework/pluginapi/plugininfo.go, framework/pluginapi/v2/pluginapi/plugininfo.go, godelgetter/download.go
==COMMIT_MSG==
Removes individual file locks as they are no longer necessary now that godel-resolver.lock is used.
==COMMIT_MSG==
=> Remove individual file locks

changelog/@unreleased/pr-541.v2.yml, resources/wrapper/godelw
Fixes #539
Concurrent invocations of godelw could fail when distribution did not already exist due to downloads going to the same file location.
==COMMIT_MSG==
Fixes issue where concurrent invocations of godelw could fail when the godel distribution did not already exist.
==COMMIT_MSG==
=> Update godelw to make resilient to concurrent downloads

changelog/@unreleased/pr-546.v2.yml, framework/artifactresolver/resolver_template.go, framework/artifactresolver/resolver_test.go
There is currently no way to extract the different parts of the "Group" field of a locator in a resolver template. We are considering creating a convention where we define the Group to be of the form "com.{GitHubOwner}.{GitHubRepo}" and would like to enable resolver templates to be defined in a manner that access these different parts, but we cannot do so with the set of template functions that are currently defined.
==COMMIT_MSG==
Adds a "GroupParts" template function to the resolver template
that returns the dot-delimited parts of the "Group" field of
a locator's "Group" field as an array.
==COMMIT_MSG==
=> Add GroupParts template function to resolver

changelog/@unreleased/pr-559.v2.yml, framework/builtintasks/installupdate/install.go
Use a lock file for the "install" operation to ensure that
it can be run concurrently safely.
Fixes #558
==COMMIT_MSG==
Makes it so that the "install" and "update" operation can be run concurrently across different godel processes safely.
==COMMIT_MSG==
=> Make the install task resilient to running concurrently

changelog/@unreleased/pr-562.v2.yml, framework/godellauncher/defaulttasks/defaulttasks.go
==COMMIT_MSG==
Updates the internal resolver used for builtin tasks to use the GitHub resolvers and updates all plugin and asset versions to use versions that have an artifact published in GitHub.
==COMMIT_MSG==
=> Update default tasks to use GitHub resolver

docsgenerator/generator/generator.go
The docsgenerator program (used by the `docs/templates/generate.sh` script to programmatically generate the documentation based on templates) fails to run with newer versions of Docker that use BuildKit.
Set the "DOCKER_BUILDKIT" environment variable to "0" when invoking
"docker build" in docsgenerator to keep the output in the legacy
format so that docsgenerator can parse it.
==COMMIT_MSG==
docsgenerator: fixes issue where docsgenerator would fail when run with new versions of Docker that use BuildKit
==COMMIT_MSG==
=> docsgenerator: make docs generator compatible with latest Docker

changelog/@unreleased/pr-578.v2.yml, framework/godellauncher/defaulttasks/defaulttasks.go
==COMMIT_MSG==
Updates versions of plugins and assets used in default tasks to versions that publish artifacts for arm64 architectures for darwin and linux and add checksums for those architectures as well.
==COMMIT_MSG==
=> Update default tasks and add checksums for arm64 architectures

changelog/@unreleased/pr-581.v2.yml, main.go
==COMMIT_MSG==
Remove go code that attempts to set GOROOT and GOPATH environment
variables on start. Should not be necessary with go modules.
==COMMIT_MSG==
=> Remove go environment variable setup in main.go

changelog/@unreleased/pr-593.v2.yml, framework/godellauncher/defaulttasks/defaulttasks.go, framework/godellauncher/defaulttasks/defaulttasks_test.go
Previously the hard-coded default resolver was used first.  This meant that even if resolvers were specified in config, godel would still attempt to reach the hard coded default (github.com).  In environments without internet access this behavior is undesirable.
Now the configured resolvers are checked first and the default is used as a fallback.
If the configured resolvers do not have most of the plugins/assets this change will cause more resolver misses.  However, these misses will only make the initial resolution slower, no functionality change is expected.  In addition, since plugins are typically cached and read from disk this increase in resolution time should not have significant effect on most workflows.
=> Reverse order of computed resolvers list

changelog/@unreleased/pr-612.v2.yml, framework/godellauncher/defaulttasks/defaulttasks.go
==COMMIT_MSG==
Updates versions of default plugins and assets to versions built using Go 1.17.
==COMMIT_MSG==
=> Update default plugins and assets to Go 1.17

changelog/@unreleased/pr-619.v2.yml, framework/builtintasks/upgradeconfig.go
Running `./godelw upgrade-config` fails if a plugin does not have a configuration file, even if the plugin itself runs properly without a configuration file.
==COMMIT_MSG==
Changes the behavior of the `upgrade-config` command such that, if the configuration for a plugin does not exist, it is ignored and treated as a success rather than a failure.
==COMMIT_MSG==
=> Make upgrade-config gracefully handle missing configuration

changelog/@unreleased/pr-630.v2.yml, resources/wrapper/godelw
When the version of openssl on the path is openssl3, the output of `openssl dgst -sha256 <file>` is different.
Older versions of openssl could output "SHA256(...)=..." while openssl3 outputs "SHA2-256(...)=...".
Using `openssl dgst -sha256 -r <file>` might be more simple to use the output (because the output format will match the alternate commands), but I have not tested this on different versions of openssl.
If openssl3 is on your path, godelw always fails to verify the hash of downloads.
==COMMIT_MSG==
fix compute_sha256 in godelw script if openssl3 is on the path
==COMMIT_MSG==
=> fix compute_sha256 if openssl3 is on the path

changelog/@unreleased/pr-695.v2.yml, godel/config/dist-plugin.yml
The `godelw` file in godel 2.71.0 does not work because the checksums in the file are populated incorrectly (and in a manner that causes a compile error for the script).
Updates logic for populating checksums in the godelw file generated using 'openssl' to trim the "SHA2-256" prefix in addition to "SHA2".
Fixes issue where versions of the 'openssl' command that used "SHA2-256" as the name of the hash algorithm for the '-sha256' flag would generate invalid godelw files.
==COMMIT_MSG==
Fixes checksums in the godelw file.
==COMMIT_MSG==
Fixes #694
=> Fix checksums in godelw generated by openssl

changelog/@unreleased/pr-886.v2.yml, framework/plugins/plugin.go
==COMMIT_MSG==
Fixes issue where the plugin cache would be attempted to be written even if the cache file path was empty.
==COMMIT_MSG==
=> Only write plugin cache file if cachePath is non-empty
